language: python
os: linux

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
  - "pypy3"
  - "pypy"

before_install:
  - pip install codecov

install:
  - pip install -e ".[testing]"

script:
  - flake8
  - pytest

after_success:
  - codecov
